package thaumcraft.common.lib;

import net.minecraft.block.SoundType;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;

public class SoundsTC {
   public static SoundEvent zap;
   public static SoundEvent heartbeat;
   public static SoundEvent spill;
   public static SoundEvent bubble;
   public static SoundEvent creak;
   public static SoundEvent squeek;
   public static SoundEvent jar;
   public static SoundEvent swarm;
   public static SoundEvent swarmattack;
   public static SoundEvent fly;
   public static SoundEvent key;
   public static SoundEvent ticks;
   public static SoundEvent clack;
   public static SoundEvent pump;
   public static SoundEvent poof;
   public static SoundEvent page;
   public static SoundEvent learn;
   public static SoundEvent write;
   public static SoundEvent erase;
   public static SoundEvent brain;
   public static SoundEvent crystal;
   public static SoundEvent wispdead;
   public static SoundEvent wisplive;
   public static SoundEvent wand;
   public static SoundEvent wandfail;
   public static SoundEvent rumble;
   public static SoundEvent ice;
   public static SoundEvent jacobs;
   public static SoundEvent hhoff;
   public static SoundEvent hhon;
   public static SoundEvent pech_idle;
   public static SoundEvent pech_trade;
   public static SoundEvent pech_dice;
   public static SoundEvent pech_hit;
   public static SoundEvent pech_death;
   public static SoundEvent pech_charge;
   public static SoundEvent shock;
   public static SoundEvent craftfail;
   public static SoundEvent scan;
   public static SoundEvent craftstart;
   public static SoundEvent runicShieldEffect;
   public static SoundEvent runicShieldCharge;
   public static SoundEvent wind;
   public static SoundEvent tool;
   public static SoundEvent gore;
   public static SoundEvent roots;
   public static SoundEvent tentacle;
   public static SoundEvent upgrade;
   public static SoundEvent whispers;
   public static SoundEvent monolith;
   public static SoundEvent infuser;
   public static SoundEvent infuserstart;
   public static SoundEvent egidle;
   public static SoundEvent egattack;
   public static SoundEvent egdeath;
   public static SoundEvent egscreech;
   public static SoundEvent crabclaw;
   public static SoundEvent crabdeath;
   public static SoundEvent crabtalk;
   public static SoundEvent chant;
   public static SoundEvent coins;
   public static SoundEvent urnbreak;
   public static SoundEvent evilportal;
   public static SoundEvent grind;
   public static SoundEvent dust;
   public static SoundEvent pageturn;
   public static SoundType GORE;
   public static SoundType CRYSTAL;
   public static SoundType JAR;
   public static SoundType URN;

   public static void registerSounds() {
      zap = getRegisteredSoundEvent("thaumcraft:zap");
      heartbeat = getRegisteredSoundEvent("thaumcraft:heartbeat");
      spill = getRegisteredSoundEvent("thaumcraft:spill");
      bubble = getRegisteredSoundEvent("thaumcraft:bubble");
      creak = getRegisteredSoundEvent("thaumcraft:creak");
      squeek = getRegisteredSoundEvent("thaumcraft:squeek");
      jar = getRegisteredSoundEvent("thaumcraft:jar");
      swarm = getRegisteredSoundEvent("thaumcraft:swarm");
      swarmattack = getRegisteredSoundEvent("thaumcraft:swarmattack");
      fly = getRegisteredSoundEvent("thaumcraft:fly");
      key = getRegisteredSoundEvent("thaumcraft:key");
      ticks = getRegisteredSoundEvent("thaumcraft:ticks");
      clack = getRegisteredSoundEvent("thaumcraft:clack");
      pump = getRegisteredSoundEvent("thaumcraft:pump");
      poof = getRegisteredSoundEvent("thaumcraft:poof");
      page = getRegisteredSoundEvent("thaumcraft:page");
      pageturn = getRegisteredSoundEvent("thaumcraft:pageturn");
      learn = getRegisteredSoundEvent("thaumcraft:learn");
      write = getRegisteredSoundEvent("thaumcraft:write");
      erase = getRegisteredSoundEvent("thaumcraft:erase");
      brain = getRegisteredSoundEvent("thaumcraft:brain");
      crystal = getRegisteredSoundEvent("thaumcraft:crystal");
      wispdead = getRegisteredSoundEvent("thaumcraft:wispdead");
      wisplive = getRegisteredSoundEvent("thaumcraft:wisplive");
      wand = getRegisteredSoundEvent("thaumcraft:wand");
      wandfail = getRegisteredSoundEvent("thaumcraft:wandfail");
      rumble = getRegisteredSoundEvent("thaumcraft:rumble");
      ice = getRegisteredSoundEvent("thaumcraft:ice");
      jacobs = getRegisteredSoundEvent("thaumcraft:jacobs");
      hhoff = getRegisteredSoundEvent("thaumcraft:hhoff");
      hhon = getRegisteredSoundEvent("thaumcraft:hhon");
      pech_idle = getRegisteredSoundEvent("thaumcraft:pech_idle");
      pech_trade = getRegisteredSoundEvent("thaumcraft:pech_trade");
      pech_dice = getRegisteredSoundEvent("thaumcraft:pech_dice");
      pech_hit = getRegisteredSoundEvent("thaumcraft:pech_hit");
      pech_death = getRegisteredSoundEvent("thaumcraft:pech_death");
      pech_charge = getRegisteredSoundEvent("thaumcraft:pech_charge");
      shock = getRegisteredSoundEvent("thaumcraft:shock");
      craftfail = getRegisteredSoundEvent("thaumcraft:craftfail");
      scan = getRegisteredSoundEvent("thaumcraft:scan");
      craftstart = getRegisteredSoundEvent("thaumcraft:craftstart");
      runicShieldEffect = getRegisteredSoundEvent("thaumcraft:runicShieldEffect");
      runicShieldCharge = getRegisteredSoundEvent("thaumcraft:runicShieldCharge");
      wind = getRegisteredSoundEvent("thaumcraft:wind");
      tool = getRegisteredSoundEvent("thaumcraft:tool");
      gore = getRegisteredSoundEvent("thaumcraft:gore");
      roots = getRegisteredSoundEvent("thaumcraft:roots");
      tentacle = getRegisteredSoundEvent("thaumcraft:tentacle");
      upgrade = getRegisteredSoundEvent("thaumcraft:upgrade");
      whispers = getRegisteredSoundEvent("thaumcraft:whispers");
      monolith = getRegisteredSoundEvent("thaumcraft:monolith");
      infuser = getRegisteredSoundEvent("thaumcraft:infuser");
      infuserstart = getRegisteredSoundEvent("thaumcraft:infuserstart");
      egidle = getRegisteredSoundEvent("thaumcraft:egidle");
      egattack = getRegisteredSoundEvent("thaumcraft:egattack");
      egdeath = getRegisteredSoundEvent("thaumcraft:egdeath");
      egscreech = getRegisteredSoundEvent("thaumcraft:egscreech");
      crabclaw = getRegisteredSoundEvent("thaumcraft:crabclaw");
      crabdeath = getRegisteredSoundEvent("thaumcraft:crabdeath");
      crabtalk = getRegisteredSoundEvent("thaumcraft:crabtalk");
      chant = getRegisteredSoundEvent("thaumcraft:chant");
      coins = getRegisteredSoundEvent("thaumcraft:coins");
      urnbreak = getRegisteredSoundEvent("thaumcraft:urnbreak");
      evilportal = getRegisteredSoundEvent("thaumcraft:evilportal");
      grind = getRegisteredSoundEvent("thaumcraft:grind");
      dust = getRegisteredSoundEvent("thaumcraft:dust");
      GORE = new SoundType(1.0F, 1.0F, gore, gore, gore, gore, gore);
      CRYSTAL = new SoundType(1.0F, 1.0F, crystal, crystal, crystal, crystal, crystal);
      JAR = new SoundType(1.0F, 1.0F, jar, jar, jar, jar, jar);
      URN = new SoundType(1.0F, 0.7F, urnbreak, urnbreak, urnbreak, urnbreak, urnbreak);
   }

   private static SoundEvent getRegisteredSoundEvent(String id) {
      SoundEvent.func_187502_a(id);
      SoundEvent soundevent = (SoundEvent)SoundEvent.field_187505_a.func_82594_a(new ResourceLocation(id));
      if (soundevent == null) {
         throw new IllegalStateException("Invalid Sound requested: " + id);
      } else {
         return soundevent;
      }
   }
}
